////////////////////////////////////////////////////////////////////////////
//                                                                        //
//  This file is part of Katana.                                          //
//                                                                        //
//  Katana is free software: you can redistribute it and/or modify        //
//  it under the terms of the GNU General Public License as published by  //
//  the Free Software Foundation, either version 3 of the License, or     //
//  any later version.                                                    //
//                                                                        //
//  Katana is distributed in the hope that it will be useful,             //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of        //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         //
//  GNU General Public License for more details.                          //
//                                                                        //
//  You should have received a copy of the GNU General Public License     //
//  along with Katana. If not, see <http://www.gnu.org/licenses/>.        //
//                                                                        //
////////////////////////////////////////////////////////////////////////////

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matteopacini_katana_KatanaAsyncTask */

#ifndef _Included_com_matteopacini_katana_KatanaAsyncTask
#define _Included_com_matteopacini_katana_KatanaAsyncTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_matteopacini_katana_KatanaAsyncTask
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_com_matteopacini_katana_KatanaAsyncTask_split
  (JNIEnv *, jclass, jstring, jstring, jstring, jlong, jlong, jboolean);

/*
 * Class:     com_matteopacini_katana_KatanaAsyncTask
 * Method:    join
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_matteopacini_katana_KatanaAsyncTask_join
  (JNIEnv *, jclass, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
