/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matteopacini_katana_KatanaAsyncTask_KatanaTaskType */

#ifndef _Included_com_matteopacini_katana_KatanaAsyncTask_KatanaTaskType
#define _Included_com_matteopacini_katana_KatanaAsyncTask_KatanaTaskType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
