/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matteopacini_katana_KatanaAsyncTask */

#ifndef _Included_com_matteopacini_katana_KatanaAsyncTask
#define _Included_com_matteopacini_katana_KatanaAsyncTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_matteopacini_katana_KatanaAsyncTask
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_com_matteopacini_katana_KatanaAsyncTask_split
  (JNIEnv *, jclass, jstring, jstring, jstring, jlong, jlong, jboolean);

/*
 * Class:     com_matteopacini_katana_KatanaAsyncTask
 * Method:    join
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_matteopacini_katana_KatanaAsyncTask_join
  (JNIEnv *, jclass, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
